image: gitpod/workspace-full
tasks:
  - init: |
      yarn install
    name: Compile gitpod-shared
    command: |
      cd gitpod-shared
      yarn compile
      gp sync-done shared
      yarn watch
  - name: Compile gitpod-web
    command: |
      cd gitpod-web
      gp sync-await shared
      yarn watch
  - name: Compile gitpod-remote
    command: |
      cd gitpod-remote
      gp sync-await shared
      yarn watch
  - name: supervisor
    before: |
      cd /workspace/gitpod/components/supervisor
    init: |
      go mod verify
  - name: gitpod-cli
    before: |
      cd /workspace/gitpod/components/gitpod-cli
    init: |
      go mod verify

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - svelte.svelte-vscode

workspaceLocation: gitpod-code/main.code-workspace
additionalRepositories:
  - url: https://github.com/gitpod-io/gitpod
    checkoutLocation: gitpod
