image: gitpod/workspace-node
tasks:
  - init: |
      yarn install
    name: Compile gitpod-shared
    command: |
      cd gitpod-shared
      yarn compile
      gp sync-done shared
      yarn watch
  - name: Compile gitpod-web
    command: |
      cd gitpod-web
      gp sync-await shared
      yarn watch
  - name: Compile gitpod-remote
    command: |
      cd gitpod-remote
      gp sync-await shared
      yarn watch

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - svelte.svelte-vscode
