# FROM alpine:3.16
FROM scratch

COPY --chown=33333:33333 out /gitpod-web/out/
COPY --chown=33333:33333 public /gitpod-web/public/
COPY --chown=33333:33333 resources /gitpod-web/resources/
COPY --chown=33333:33333 package.json package.nls.json README.md LICENSE.txt /gitpod-web/
