name: Release gitpod-remote

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Update Segment
        working-directory: ./gitpod-remote
        run: |
          set -e
          setSegmentKey="setpath([\"segmentKey\"]; \"untrusted-dummy-key\")"
          jqCommands="${setSegmentKey}"
          cat package.json | jq "${jqCommands}" > package.json.tmp
          mv package.json.tmp package.json

      - name: Package extension
        id: package_vsix
        run: |
          set -e
          yarn run compile:gitpod-shared

          cd gitpod-remote
          yarn package
          echo "vsix_path=$(ls *.vsix)" >> $GITHUB_OUTPUT
          echo "version=$(jq --raw-output '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Publish to MS Marketplace
        working-directory: ./gitpod-remote
        run: |
          npx vsce publish --packagePath ${{ steps.package_vsix.outputs.vsix_path }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX Registry
        run: |
          npx ovsx publish --packagePath ${{ steps.package_vsix.outputs.vsix_path }}
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_PAT }}
